// <auto-generated />
namespace plkjStaffWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addfullnamr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfullnamr));
        
        string IMigrationMetadata.Id
        {
            get { return "201709080531003_addfullnamr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
