//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace plkjStaffWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class zq_CustomerTable
    {

        public int id { get; set; }

        [Required]
        [Display(Name = "客户姓名")]
        public string customerName { get; set; }

        [Required]
        [Display(Name = "客户电话")]
        public string customerPhone { get; set; }

        [Display(Name = "客户留言")]
        public string customerMessage { get; set; }
    }
}
